name: 'scanio'
description: 'scanio description'
inputs:
  scanner:  # scanner to use for analysis
    description: 'scanner to use for analysis'
    required: false
    default: 'semgrep'
  checkout_path:
    description: "The path at which the analyzed repository was checked out. Used to relativize any absolute paths in the uploaded SARIF file."
    required: false
    default: ${{ github.workspace }}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/scan-io-git/scan-io:main'
  args:
    - analyse
    - '--scanner'
    - ${{ inputs.scanner }}
    - '--format'
    - sarif
    - ${{ inputs.checkout_path }}
