name: 'scanio'
description: 'scanio description'
inputs:
  scanner:  # scanner to use for analysis
    description: 'scanner to use for analysis'
    required: false
    default: 'semgrep'
  checkout_path:
    description: "The path at which the analyzed repository was checked out. Used to relativize any absolute paths in the uploaded SARIF file."
    required: false
    default: '.'  # ${{ github.workspace }}
  format:  # format of the output
    description: 'format of the output'
    required: false
    default: 'sarif'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/scan-io-git/scan-io:v0.2.0'
  args:
    - analyse
    - '--scanner'
    - ${{ inputs.scanner }}
    - '--format'
    - ${{ inputs.format }}
    - ${{ inputs.checkout_path }}
