name: 'scanio'
description: 'scanio description'
inputs:
  scanner:  # scanner to use for analysis
    description: 'scanner to use for analysis'
    required: true
    default: 'semgrep'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/scan-io-git/scan-io:main'
  args:
    - analyse
    - '--scanner'
    - ${{ inputs.scanner }}
