name: 'scanio'
description: 'scanio description'
inputs:
  scanner:  # scanner to use for analysis
    description: 'scanner to use for analysis'
    required: false
    default: 'semgrep'
  checkout_path:
    description: "The path at which the analyzed repository was checked out. Used to relativize any absolute paths in the uploaded SARIF file."
    required: false
    default: '.'  # ${{ github.workspace }}
  format:  # format of the output
    description: 'format of the output'
    required: false
    default: 'sarif'
  extra_args:
    description: 'Additional arguments to pass to the command'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/scan-io-git/scan-io:v0.2.0'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      set -e
      ARGS="analyse --scanner ${{ inputs.scanner }} --format ${{ inputs.format }} ${{ inputs.checkout_path }}"
      if [ -n "${{ inputs.extra_args }}" ]; then
        ARGS="$ARGS -- ${{ inputs.extra_args }}"
      fi
      exec scanio $ARGS
